### ISSUE TITLE
OFAC DOBs are all blank

### ISSUE THREAD

**Issue by marc-fez** [opensanctions/us-ofac#1]
Looking at some of the OFAC entries, I noticed that the dates of birth are all blank. Double checking on the OFAC site, at least some of the entities I checked do have dates of birth where they are missing from the OpenSanctions.org main master.ijson and the us-ofac.ijson files. The quality enum is populated, but not the date. I'm not sure, but it looks like the code in scraper.py on line 84 is actually setting an object property of birth_date.place rather than birth_date.date.

```
 for pob in entry.findall('./dateOfBirthList/dateOfBirthItem'):
        birth_date = entity.create_birth_date()
        birth_date.place = parse_date(pob.findtext('./dateOfBirth'))
        birth_date.quality = BirthDate.QUALITY_WEAK
        if pob.findtext('./mainEntry') == 'true':
            birth_date.quality = BirthDate.QUALITY_STRONG
```

**Comment by pudo** [comment]
Fixed in #2.
